name: security_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.7
  agora_rtm: ^1.0.0
  cloud_firestore: ^2.4.0
  contacts_service: ^0.6.1
  cool_alert: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  firebase: ^9.0.1
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  flutter:
    sdk: flutter
  flutter_contact: ^0.9.1+7
  flutter_polyline_points: ^1.0.0
  flutter_sound: ^8.3.9
  flutter_speed_dial: ^4.2.0
  flutter_zoom_drawer: ^2.1.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  hexcolor: ^2.0.4
  image_picker: ^0.8.3+2
  intl_phone_number_input: ^0.7.0+2
  intro_slider: ^3.0.2
  keyboard_actions: ^3.4.3
  libphonenumber_web: ^0.2.0+1
  otp_text_field: ^1.1.1
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  pin_code_fields: ^7.3.0
  provider: ^6.0.0
  readmore: ^2.1.0
  rounded_loading_button: ^2.0.6
  screenshot: ^1.2.3
  searchfield: ^0.5.2
  social_share: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    #   - images/a_dot_ham.jpeg
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
